### ISSUE TITLE
Create "not empty" filter for directories

### ISSUE THREAD

**Issue by jc-a3s** [data-hunters/metadata-digger#20]
Please create Processing Pipeline Filter. Scope:
- [x] Create Spark UDF which iterates over specified Metatada Directories in DF and verifies if they are not empty
- [x] Build appropriate `Filter` class
- [x] Add Filter to `BasicExtractionWorkflow`
- [x] Prepare configuration class to allow user include required directories. 
- [x] Add description in README

**Comment by dawidsau** [comment]
Mandatory directories filter implemented.
